- name: 读取 kubelet.conf 文件 stat 信息
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf_stat

- block:
  - name: 创建 kubernetes 相关目录
    file: 
      name: "{{ item }}"
      state: directory
    with_items:
    - "{{ kubelet_root_dir }}"
    - /usr/share/bash-completion/completions

  - name: 确认 kubelet 已停止运行
    service:
      name: kubelet
      state: stopped
      enabled: yes

  - name: 获取 Docker Cgroup Driver 值
    shell: docker info --format '{{ '{{' }} json .CgroupDriver {{ '}}' }}' | cut -d'"' -f2
    register: docker_cgroup_driver

  - name: 设置变量 DOCKER_CGROUP_DRIVER
    set_fact: DOCKER_CGROUP_DRIVER="{{ docker_cgroup_driver.stdout }}"

  - name: 创建 kubeadm 的配置文件
    template: 
      src: kubeadm-config.yaml.j2
      dest: /etc/kubernetes/kubeadm-config.yaml
      owner: root
      mode: 0644
      backup: yes

  - name: Worker 节点加入集群
    shell: >
      kubeadm join --config /etc/kubernetes/kubeadm-config.yaml 
      --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests

  when: 
  - inventory_hostname in (groups['kube-worker'] + groups['new-worker'])
  - inventory_hostname not in (groups['kube-master'] + groups['new-master'])
  - not kubelet_conf_stat.stat.exists

- name: 取消在 worker 组的 master 节点 taint，使 master 节点可以调度
  shell: >
    kubectl taint nodes {{inventory_hostname}} node-role.kubernetes.io/master='':NoSchedule --overwrite &&
    kubectl taint nodes {{inventory_hostname}} node-role.kubernetes.io/master-
  delegate_to: "{{ managed_by_choerodon and inventory_hostname or groups['kube-master']|first }}"
  ignore_errors: yes
  when: 
  - inventory_hostname in (groups['kube-worker'] + groups['new-worker'])
  - inventory_hostname in (groups['kube-master'] + groups['new-master']) 